// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToMarkdown(arg1) {
  return window['go']['main']['App']['ExportToMarkdown'](arg1);
}

export function ExportToPDF() {
  return window['go']['main']['App']['ExportToPDF']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenMarkdownFile() {
  return window['go']['main']['App']['OpenMarkdownFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveMarkdownFile(arg1) {
  return window['go']['main']['App']['SaveMarkdownFile'](arg1);
}

export function SavePDFFile(arg1) {
  return window['go']['main']['App']['SavePDFFile'](arg1);
}
