// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function ExportToMarkdown(arg1:core.GlossDocument):Promise<string>;

export function ExportToPDF():Promise<void>;

export function OpenFile():Promise<core.GlossDocument>;

export function SaveFile(arg1:core.GlossDocument):Promise<string>;

export function SaveMarkdownFile(arg1:core.GlossDocument):Promise<string>;

export function SavePDFFile(arg1:core.GlossDocument):Promise<string>;
